export { default as DatedOfToday } from "./components/DatedOfToday";
export { default as RemoveDancer } from "./components/RemoveDancer";
export { default as AddCouple } from "./components/AddCouple";
export { default as InputOrden } from "./components/InputOrden";
export { default as InputDancerName } from "./components/InputDancerName";
export { default as JudgeButtons } from "./components/AddRemoveJudges";
export { default as AverageScore } from "./components/InputAverange";
export { default as SendDataButton } from "./components/SendDataButton";
export { default as JudgeScoreInput } from "./components/InputJudge";
export { default as EditableJudgeName} from "./components/EditableJudgeName";